Models/ApplicationDbContext.cs
using System;
using Microsoft.EntityFrameworkCore;
using ForgingAhead.Models;

namespace ForgingAhead.Models
{
	public class ApplicationDbContext : DbContext
	{
		public ApplicationDbContext(DbContextOptions options) : base (options){}

		public DbSet<Character> Characters {get; set;}

		public DbSet<Equipment> Equipments {get; set;}

		public DbSet<EquipChar> EquipChars {get;set;}

		protected override void OnModelCreating(ModelBuilder modelBuilder)
		{
			modelBuilder.Entity<EquipChar>()
				.HasKey(t => new {t.EquipmentId, t.CharacterId});

			modelBuilder.Entity<EquipChar>()
				.HasOne(eq => eq.Equipment)
				.WithMany(p => p.EquipChars)
				.HasForeignKey(eq => eq.EquipmentId);

			modelBuilder.Entity<EquipChar>()
				.HasOne(ch => ch.Character)
				.WithMany(p => p.EquipChars)
				.HasForeignKey(ch => ch.CharacterId);
		}
	}
}

Models/Character.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace ForgingAhead.Models
{
    public class Character
    {
        [Key]
        public int ID {get; set;}
        public string Name {get; set;}
        [Display(Name="is Active")]
        public bool isActive {get; set;}
        public int Level {get; set;}
        public int Strength {get; set;}
        public int Dexterity {get; set;}
        public int Intelligence {get; set;}

        public List<EquipChar> EquipChars {get; set;}
    }
}

Models/EquipChar.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ForgingAhead.Models
{
	public class EquipChar
	{
		public int EquipmentId {get;set;}
		public Equipment Equipment {get;set;}

		public int CharacterId {get;set;}
		public Character Character {get;set;}

		public bool IsEquiped {get;set;}
	}
}

Models/Equipment.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace ForgingAhead.Models
{
    public class Equipment
    {
        [Key]
        public int ID {get; set;}
        public string Name {get; set;}
        public int Preco {get; set;}
        public string Tipo {get; set;}

        public List<EquipChar> EquipChars {get;set;}
    }
}

Controllers/CharacterController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using ForgingAhead.Models;
using System.Linq;
using System.ComponentModel.DataAnnotations;

namespace ForgingAhead.Controllers
{
	public class CharacterController : Controller
	{
		private readonly ApplicationDbContext _context;

		public CharacterController(ApplicationDbContext context)
		{
			_context = context;
		}

		public IActionResult Index()
		{
			ViewData["Title"] = "Characters";
			var model = _context.Characters.OrderBy(e => e.Name).ToList();
			return View(model);
		}

		public IActionResult GetActive()
		{
			ViewData["Title"] = "Active Characters";
			var model = _context.Characters.Where(e => e.isActive).OrderBy(e => e.Name).ToList();
			return View("Index", model);
		}

		public IActionResult Details(string name)
		{
			var model = _context.Characters.FirstOrDefault(e => e.Name == name);
			return View(model);
		}
		
		public IActionResult Create() 
		{
			ViewData["Title"] = "Create Character";
			return View();
		}

		[HttpPost]
		public IActionResult Create(Character character)
		{
				_context.Characters.Add(character);
				_context.SaveChanges();
				return RedirectToAction("Index");
		}

		public IActionResult Update(int id) 
		{
			var model = _context.Characters.FirstOrDefault(e => e.ID == id);
			return View(model);
		}

		[HttpPost]
		public IActionResult Update(Character character)
		{
			_context.Entry(character).State = EntityState.Modified;
			_context.SaveChanges();
			return RedirectToAction("Index");
		}

		public IActionResult Delete(int id)
		{
			var original = _context.Characters.FirstOrDefault(e => e.ID == id);
			if(original != null)
			{
				_context.Characters.Remove(original);
				_context.SaveChanges();
			}
			return RedirectToAction("Index");
		}
	}
}

Controllers/EquipCharController.cs
using ForgingAhead.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel.DataAnnotations;

namespace ForgingAhead.Controllers
{
	public class EquipCharController : Controller
	{
		private readonly ApplicationDbContext _context;

		public EquipCharController(ApplicationDbContext context)
		{
			_context = context;
		}

		public IActionResult Index()
		{
			ViewData["Title"] = "List of Equipments Per Character";
			var model = _context.EquipChars.OrderBy(c => c.CharacterId).ToList();
			return View(model);
		}

		public IActionResult EquipPerChar(int id)
		{
			ViewData["Title"] = "Equipment per Character";
			//var model = _context.EquipChar.Include(Character).Include(Equipment).FromSql("SELECT characters.Name, equipmentspercharacter.*, equipments.Name, equipments.Tipo	FROM equipmentspercharacter INNER JOIN characters ON characters.ID = equipmentspercharacter.CharacterId INNER JOIN equipments ON equipments.ID = equipmentspercharacter.EquipmentId WHERE (characters.ID = 3 AND equipmentspercharacter.IsEquiped =1)").ToList();
			var model = _context.Characters.Include(ec => ec.EquipChars).ThenInclude(e => e.Equipment).ToList();
			return View(model);
		}
	}
}

Controllers/EquipmentController.cs
using ForgingAhead.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel.DataAnnotations;

namespace ForgingAhead.Controllers
{
	public class EquipmentController : Controller
	{
		private readonly ApplicationDbContext _context;

		public EquipmentController(ApplicationDbContext context)
		{
			_context =  context;
		}

		public IActionResult Index() 
		{
			ViewData["Title"] = "List fo Equipments";
			var model = _context.Equipments.OrderBy(c => c.ID).ToList();
			return View(model);
		}

		public IActionResult Details(int id)
		{
			ViewData["Title"] = "Details of Equipment";
			var model = _context.Equipments.FirstOrDefault(c => c.ID == id);
			return View(model);
		}

		public IActionResult Create()
		{
			ViewData["Title"] = "Create new Equipment";
			return View();
		}

		[HttpPost]
		public IActionResult Create(Equipment equipment)
		{
			_context.Equipments.Add(equipment);
			_context.SaveChanges();
			return RedirectToAction("Index");
		}

		public IActionResult Update(int id)
		{
			ViewData["Title"] = "Update equipment";
			var model = _context.Equipments.FirstOrDefault(c => c.ID == id);
			return View(model);
		}

		[HttpPost]
		public IActionResult Update(Equipment equipment)
		{
			_context.Entry(equipment).State = EntityState.Modified;
			_context.SaveChanges();
			return RedirectToAction("Index");
		}

		public IActionResult Delete(int id)
		{
			var original = _context.Equipments.FirstOrDefault(c => c.ID == id);
			if (original != null)
			{
				_context.Equipments.Remove(original);
				_context.SaveChanges();
			}
			return RedirectToAction("Index");
		}
	}
}

Views/Character/Create.cshtml
@model ForgingAhead.Models.Character 
@section header {
	<meta name="description" content="Form for creating a character in ForgingAhead"> 
}

<div class="panel panel-default">
	<div class="panel-heading">
		<h3>Create</h3>
	</div>
	<div class="panel-body">
		<form asp-action="Create" asp-controller="Character">
			<div class="form-horizontal">
				<h4>Character</h4>
				<hr />

				<div class="form-group">
					<label class="control-label col-md-2" asp-for="Name"></label>
					<div class="col-md-6">
						<input type="text" class="form-control" asp-for="Name" />
					</div>
				</div>

				<div class="form-group">
					<label class="control-label col-md-2" asp-for="Level"></label>
					<div class="col-md-6">
						<input type="number" class="form-control" asp-for="Level" />
					</div>
				</div>

				<div class="form-group">
					<label class="control-label col-md-2" asp-for="Strength"></label>
					<div class="col-md-6">
						<input class="form-control" asp-for="Strength" />
					</div>
				</div>

				<div class="form-group">
					<label class="control-label col-md-2" asp-for="Dexterity"></label>
					<div class="col-md-6">
						<input class="form-control" asp-for="Dexterity" />
					</div>
				</div>

				<div class="form-group">
					<label class="control-label col-md-2" asp-for="Intelligence"></label>
					<div class="col-md-6">
						<input class="form-control" asp-for="Intelligence" />
					</div>
				</div>

				<div class="form-group">
					<div class="col-md-offset-2 col-md-6">
						<div class="checkbox">
							<label asp-for="isActive">
            <input type="checkbox" id="isActive" name="isActive" value="true" /> Is Active
          </label>
						</div>
					</div>
				</div>

				<div class="form-group">
					<div class="col-md-offset-2 col-md-10">
						<button type="submit" class="btn btn-default">Create</button>
						<button type="" class="btn btn-danger">Go Back</button>
					</div>
				</div>

			</div>
		</form>
	</div>
</div>

Views/Character/Details.cshtml
@model ForgingAhead.Models.Character

<h1>Character Details</h1>
@Html.Partial("_CharacterSheet",Model)

Views/Character/Index.cshtml
@model List<ForgingAhead.Models.Character>

@section header {
  <meta name="description" content="List of all characters in ForgingAhead">
}

  <h1>Character</h1>
  <p>
    <a asp-action="Create" asp-controller="Character"/>Create new character</a>
  </p>

  <div class="row">
    @foreach (var item in Model)
    {
      @Html.Partial("_CharacterSheet", item)
    }
  </div>
  

Views/Character/Update.cshtml
@model ForgingAhead.Models.Character 
@section header {
	<meta name="description" content="Form for updating a character in ForgingAhead"> 
}

<div class="panel panel-default">
	<div class="panel-heading">
		<h3>Create</h3>
	</div>
	<div class="panel-body">
		<form asp-action="Update" asp-controller="Character">
      <input type="hidden" asp-for="ID" value="@Model.ID" />
			<div class="form-horizontal">
				<h4>Character</h4>
				<hr />

				<div class="form-group">
					<label class="control-label col-md-2" asp-for="Name"></label>
					<div class="col-md-6">
						<input type="text" class="form-control" asp-for="Name" value="@Model.Name" />
					</div>
				</div>

				<div class="form-group">
					<label class="control-label col-md-2" asp-for="Level"></label>
					<div class="col-md-6">
						<input type="number" class="form-control" asp-for="Level" value="@Model.Level"/>
					</div>
				</div>

				<div class="form-group">
					<label class="control-label col-md-2" asp-for="Strength"></label>
					<div class="col-md-6">
						<input class="form-control" asp-for="Strength" value="@Model.Strength"/>
					</div>
				</div>

				<div class="form-group">
					<label class="control-label col-md-2" asp-for="Dexterity"></label>
					<div class="col-md-6">
						<input class="form-control" asp-for="Dexterity" value="@Model.Dexterity"/>
					</div>
				</div>

				<div class="form-group">
					<label class="control-label col-md-2" asp-for="Intelligence"></label>
					<div class="col-md-6">
						<input class="form-control" asp-for="Intelligence" value="@Model.Intelligence"/>
					</div>
				</div>

				<div class="form-group">
					<div class="col-md-offset-2 col-md-6">
						<div class="checkbox">
							<label asp-for="isActive">
            <input type="checkbox" id="isActive" name="isActive" value="@Model.isActive" /> Is Active
          </label>
						</div>
					</div>
				</div>

				<div class="form-group">
					<div class="col-md-offset-2 col-md-10">
						<button type="submit" class="btn btn-default">Update</button>
						<button type="reset" class="btn btn-danger">Go Back</button>
					</div>
				</div>

			</div>
		</form>
	</div>
</div>

Views/EquipChar/EquipPerChar.cshtml
@model List<ForgingAhead.Models.EquipChar>

  <ul>
    @foreach (var item in Model)
    {
      <li>@item.CharacterId</li>
    }
  </ul>

Views/EquipChar/Index.cshtml
@model List<ForgingAhead.Models.EquipChar>

  <h1>Charater With Equipments</h1>

  <p>
    <a asp-action="Index" asp-controller="Character">Home</a>
  </p>

  <div class="row">
    <ul>
    @foreach (var item in Model)
    {
      <li>@item.CharacterId || @item.EquipmentId</li>
    }
    </ul>
  </div>

Views/Equipment/Create.cshtml
@model ForgingAhead.Models.Equipment
@section header {
  <meta name="description" content="Form for creating a equipment in ForgingAhead">
}

<div class="panel panel-default">
  <div class="panel-heading">
    <h3>Create</h3>
  </div>
  <div class="panel-body">
    <form asp-action="Create" asp-controller="Equipment">
      <div class="form-horizontal">
        <h4>Equipment</h4>
        <hr />

        <div class="form-group">
          <label class="control-label col-md-2" asp-for="Name"></label>
          <input type="text" class="form-control" asp-for="Name" />
        </div>

        <div class="form-group">
          <label class="control-label col-md-2" asp-for="Preco"></label>
          <input type="number" class="form-control" asp-for="Preco" />
        </div>

        <div class="form-group">
          <label class="control-label col-md-2" asp-for="Tipo"></label>
          <input type="text" class="form-control" asp-for="Tipo" />
        </div>

        <div class="form-group">
          <div class="col-md-offset-2 col-md-10">
            <button type="submit" class="btn btn-success">Create</button>
            <button type="reset" class="btn btn-danger">Clear</button>
          </div>
        </div>

      </div>
    </form>
  </div>
</div>

Views/Equipment/Details.cshtml
@model ForgingAhead.Models.Equipment

<h1>Equipment Detail</h1>
@Html.Partial("_EquipmentSheet",Model)

Views/Equipment/Index.cshtml
@model List<ForgingAhead.Models.Equipment>

@section header {
  <meta name="description" content="List of all equipments in ForgingAhead">
}

  <h1>Equipments</h1>
  <p>
    <a asp-action="Create" asp-controller="Equipment">Create new Equipment</a>
  </p>

  <div class="row">
    @foreach(var item in Model)
    {
      @Html.Partial("_EquipmentSheet", item)
    }
  </div>

Views/Shared/_CharacterSheet.cshtml
@model ForgingAhead.Models.Character

@section header {
  <meta name="description" content="List of all characters in ForgingAhead">
}

<div class="col-md-5 bordered-div card-image-paper">
  <h4 class="card-name">@Model.Name</h4>
  <div class="pull-right">
    <a asp-action="Details" asp-controller="Character" asp-route-name="@Model.Name"><span class="glyphicon glyphicon-user"></span></a>
    <a asp-action="Update" asp-controller="Character" asp-route-id="@Model.ID"><span class="glyphicon glyphicon-pencil"></span></a>
    <a asp-action="Delete" asp-controller="Character" asp-route-id="@Model.ID"><span class="glyphicon glyphicon-trash"></span></a>
  </div>

  <hr />
  <div class="col-md-8 card-content">
    <div class="form-group">
      <label asp-for="Level" class="control-label col-md-8"></label>
      <div class="col-md-4">
        <p class="form-control-static">@Model.Level</p>
      </div>
      <label asp-for="Strength" class="control-label col-md-8"></label>
      <div class="col-md-4">
        <p class="form-control-static">@Model.Strength</p>
      </div>
      <label asp-for="Dexterity" class="control-label col-md-8"></label>
      <div class="col-md-4">
        <p class="form-control-static">@Model.Dexterity</p>
      </div>
      <label asp-for="Intelligence" class="control-label col-md-8"></label>
      <div class="col-md-4">
        <p class="form-control-static">@Model.Intelligence</p>
      </div>
    </div>
  </div>
</div>

Views/Shared/_EquipmentSheet.cshtml
@model ForgingAhead.Models.Equipment

@section header {
  <meta name="description" content="List of all equipment in ForgingAhead">
}

<div class="col-md-5 bordered-div">
  <h4>@Model.Name</h4>
  <div class="pull-right">
    <a asp-action="Details" asp-controller="Equipment" asp-route-id="@Model.ID"><span class="glyphicon glyphicon-user"></span></a>
    <a asp-action="Update" asp-controller="Equipment" asp-route-id="@Model.ID"><span class="glyphicon glyphicon-pencil"></span></a>
    <a asp-action="Delete" asp-controller="Equipment" asp-route-id="@Model.ID"><span class="glyphicon glyphicon-trash"></span></a>
  </div>

  <hr />
  <div class="col-md-6">
    <div class="form-group">
      <label asp-for="Preco" class="control-label col-md-8"></label>
      <div class="col-sm-3">
        <p class="form-control-static">@Model.Preco</p>
      </div>
      <label asp-for="Tipo" class="control-label col-md-8"></label>
      <div class="col-sm-3">
        <p class="form-control-static">@Model.Tipo</p>
      </div>
    </div>
  </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport", content="width=device-width, initial-scale=1.0">
    <title>@ViewData["Title"] - ForgingAhead</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true">
    @RenderSection("header", required: false)
  </head>
  <body>
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#collapse-menu" aria-expanded="false">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a asp-area="" asp-controller="Character" asp-action="Index" class="navbar-brand">Home</a>
        </div>

        <div class="collapse navbar-collapse" id="collapse-menu">
          <ul class="nav navbar-nav">
            <li>
              <a asp-area="" asp-controller="Character" asp-action="Create">Create</a>
            </li>
            <li>
              <a asp-area="" asp-controller="Character" asp-action="GetActive">Active</a>
            </li>
            <li>
              <a asp-area="" asp-controller="Equipment" asp-action="Index">Equipments</a>
            </li>
          </ul>
      </div>

      </div>
    </div>
      <div class="container">
        @RenderBody()
      </div>      
    </div>
    <hr />
    <footer class="footer">
      <div class="container">
        <div class="texto-footer">
          <p>&copy; 2016 - ForgingAhead</p>
        </div>
      </div>
    </footer>
  </body>
</html>